# Generated by Django 4.1.4 on 2022-12-28 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LittleLemonDRF', '0002_rename_slud_category_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='quantiy',
            new_name='quantity',
        ),
    ]
